server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://heatmapserver.mysql.database.azure.com:3306/heatmap_db?useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: nscbmfjpoo
    password: ZjZl$QfIyHFsIMG9
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: verySecretKeyChangeMeVerySecretKey1234567890
  expiration-ms: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
